### ISSUE TITLE
Can't access any files

### ISSUE THREAD

**Issue by SarahBoening** [yaxirhuxxain/Source-Code-Suggestion#1]
I'm trying to use your model, but I can't download any of the files. The links in the README link to a Chinese website I'm not able to understand and some passwords do not seem to work. So, I am unsure what I need to do to download the files.
Would it be possible for you to provide me with your files for reproduction?

**Comment by PikachuHy** [comment]
Hi, I met the same problem. And I find that
https://github.com/yaxirhuxxain/Source-Code-Suggestion/blob/master/Links
```

JavaFiles
Password: qpp4

Vectors
Password: 3hlp

SavedModels
Password: l9ml

SourceCode
Password: 0wm1
```

this is the baidupan access code, but the last one is error.

**Comment by yaxirhuxxain** [comment]
These are Baidu cloud drive links. You need the codes provided in links file as mentioned by #PikachuHy. Please follow the updated ReadME for ease of usage. You can load any of the saved models and use the preprocessed Vectors to evaluate the models.
